name: Deploy to GitHub Pages

on:
  push:
    branches: ["fix/appsmanager-useeffect"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install and Build
        working-directory: ./frontend
        run: |
          npm cache clean --force
          npm install --legacy-peer-deps
          npx npm-check-updates -y || true
          npm run build
          
